name: GeneratorPlugin
author: ScienceMan
version: 1.0
main: me.ScienceMan.generatorplugin.Main
description: Generator Plugin
depend: [Vault]
api-version: 1.15

commands:
  buygenerator:
    usage: /<command> 
    description: Allows player to purchase a Generator
  reloadgenerators:
    usage: /<command>
    description: Reloads the configs and generators
  generatorinfo:
    usage: /<command>
    description: Gets the generator pricing info